### ISSUE TITLE
Make a tag/release for PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [masonproffitt/pyhep-2022-abcd-pyhf#2]
Hello @masonproffitt, can you kindly prepare the tag/release so that I then use it to mint a DOI on Zenodo and attach it to the workshop "proceedings" https://zenodo.org/communities/pyhep2022? Advance thanks.

**Comment by masonproffitt** [comment]
Sure, I've created a release now: https://github.com/masonproffitt/pyhep-2022-abcd-pyhf/releases/tag/v1
